<section id="aira-opportunity-radar" class="bg-white py-16 md:py-24" aria-labelledby="aira-radar-title">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid lg:grid-cols-[0.92fr_1.08fr] gap-8 lg:gap-12 items-center">
            <div>
                <div class="inline-flex items-center gap-2 text-sm font-bold uppercase tracking-[0.14em] text-[#008B8B]"><span class="w-2 h-2 rounded-full bg-[#40E0D0] shadow-[0_0_0_5px_rgba(64,224,208,.13)]"></span>AIRA Tender Radar · publieke preview</div>
                <h2 id="aira-radar-title" class="mt-4 text-3xl md:text-5xl font-bold tracking-[-0.02em] text-[#07111f]">Van open signaal naar een verdedigbare kans.</h2>
                <p class="mt-5 text-lg leading-relaxed text-slate-600">Tender Radar verzamelt publieke kansen, normaliseert de bronnen en rangschikt ze op inhoudelijke fit, haalbaarheid, urgentie en bewijs. Zo ziet een organisatie niet alleen <em>wat</em> er is, maar ook <em>waarom</em> een kans aandacht verdient.</p>
                <div class="mt-7 grid sm:grid-cols-2 gap-3 text-sm"><div class="rounded-2xl border border-slate-200 p-4"><strong class="block text-[#07111f]">Meerdere bronnen</strong><span class="mt-1 block text-slate-500">EU, NL en internationale openbare signalen.</span></div><div class="rounded-2xl border border-slate-200 p-4"><strong class="block text-[#07111f]">Actor-fit</strong><span class="mt-1 block text-slate-500">Kansen beoordeeld tegen organisatiecontext en capabilities.</span></div><div class="rounded-2xl border border-slate-200 p-4"><strong class="block text-[#07111f]">Geen zwarte doos</strong><span class="mt-1 block text-slate-500">Bron, fit, onzekerheid en urgentie blijven zichtbaar.</span></div><div class="rounded-2xl border border-slate-200 p-4"><strong class="block text-[#07111f]">Mens beslist</strong><span class="mt-1 block text-slate-500">De radar ondersteunt de go/no-go; hij neemt die niet over.</span></div></div>
                <div class="mt-8 flex flex-col sm:flex-row gap-3"><a href="/opportunity-radar-preview" class="inline-flex justify-center rounded-full bg-[#07111f] px-6 py-3.5 font-bold text-white hover:bg-[#12243a] transition">Open de live radar</a><a href="{{ route('contact') }}" class="inline-flex justify-center rounded-full border border-slate-300 px-6 py-3.5 font-bold text-[#2E4462] hover:bg-slate-50 transition">Bespreek uw use-case</a></div>
            </div>
            <div class="relative overflow-hidden rounded-[28px] border border-[#153247] bg-[#030a12] p-4 md:p-5 shadow-2xl shadow-slate-900/20" aria-label="Voorbeeld van de AIRA Tender Radar interface">
                <div class="flex items-center justify-between border-b border-cyan-200/10 pb-4 text-[11px] font-mono tracking-[0.12em] text-slate-500"><span>AIRA / OPPORTUNITY RADAR</span><span class="inline-flex items-center gap-2 text-emerald-300"><i class="w-2 h-2 rounded-full bg-emerald-300 animate-pulse"></i> LIVE SIGNALS</span></div>
                <div class="mt-5 grid md:grid-cols-[1fr_190px] gap-4">
                    <div class="relative aspect-square max-h-[420px] rounded-2xl border border-cyan-200/10 bg-[radial-gradient(circle_at_center,rgba(64,224,208,.18),transparent_12%,rgba(10,53,67,.35)_13%,rgba(3,10,18,.95)_64%)] overflow-hidden"><div class="absolute inset-[12%] rounded-full border border-cyan-200/10"></div><div class="absolute inset-[27%] rounded-full border border-cyan-200/10"></div><div class="absolute inset-[42%] rounded-full border border-cyan-200/15"></div><div class="absolute left-1/2 top-1/2 w-[46%] h-px origin-left -rotate-[28deg] bg-gradient-to-r from-[#40E0D0]/70 to-transparent"></div><div class="absolute left-[48%] top-[48%] w-4 h-4 rounded-full bg-[#40E0D0] shadow-[0_0_24px_rgba(64,224,208,.8)]"></div><span class="absolute left-[24%] top-[32%] w-3 h-3 rotate-45 bg-amber-300 shadow-[0_0_16px_rgba(252,211,77,.45)]"></span><span class="absolute right-[20%] top-[25%] w-3 h-3 rounded-full bg-cyan-300 shadow-[0_0_16px_rgba(103,232,249,.45)]"></span><span class="absolute right-[30%] bottom-[24%] w-4 h-4 rounded-full border-2 border-emerald-300 bg-emerald-300/20"></span><span class="absolute left-[30%] bottom-[18%] w-2.5 h-2.5 rounded-full bg-fuchsia-300"></span><div class="absolute bottom-4 left-4 right-4 flex justify-between text-[10px] font-mono text-slate-500"><span>AFSTAND = FIT</span><span>GROOTTE = POTENTIEEL</span></div></div>
                    <div class="grid gap-3 content-start"><div class="rounded-xl border border-white/10 bg-white/[0.04] p-4"><div class="text-[10px] uppercase tracking-[0.14em] text-slate-500">Top fit</div><div class="mt-2 text-2xl font-bold text-cyan-200">86%</div><div class="mt-1 text-xs text-slate-500">inhoudelijke match</div></div><div class="rounded-xl border border-white/10 bg-white/[0.04] p-4"><div class="text-[10px] uppercase tracking-[0.14em] text-slate-500">Bronstatus</div><div class="mt-2 font-bold text-white">Open data</div><div class="mt-1 text-xs text-slate-500">inspecteerbaar</div></div><div class="rounded-xl border border-white/10 bg-white/[0.04] p-4"><div class="text-[10px] uppercase tracking-[0.14em] text-slate-500">Besluit</div><div class="mt-2 font-bold text-amber-200">Review</div><div class="mt-1 text-xs text-slate-500">menselijke go/no-go</div></div></div>
                </div>
            </div>
        </div>
    </div>
</section>
